server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:facturacion_db
    username: lisandroEkruger
    password: lisandroEkruger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
